apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vaultpay-monitor
  namespace: vaultpay-ns
  labels:
    app: vaultpay
    release: monitoring
spec:
  selector:
    matchLabels:
      app: vaultpay
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - vaultpay-ns
