apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secure-app-monitor
  namespace: secure-app-ns
  labels:
    app: secure-app
    release: monitoring
spec:
  selector:
    matchLabels:
      app: secure-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - secure-app-ns
